[book]
authors = ["pandazhangs"]
language = "zh"
multilingual = false
src = "src"
title = "panda note :)"
description = "The note book of pandazhangs"
[output.html]
mathjax-support = true
additional-css = ["js/whichlang.css"]
additional-js = [
    "js/fzf.umd.js",
    "js/elasticlunr.js",
    "js/import-html.js",
    "js/whichlang.js",
]
input-404 = "../README.md"
[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
